pipeline:
  update-spectrum:
    image: no-cloud.fr/eve/git
    commands:
      - /eve.sh git://github.com/hanzz/spectrum2.git master SPECTRUM_VERSION maestro-spectrum/Dockerfile

  deploy:
    image: no-cloud.fr/eve/git
    commands:
      - git config --global user.name "Eve"
      - git config --global user.email "eve@no-cloud.fr"
      - git config --global push.default simple
      - echo ${DRONE_REPO_LINK} | sed -e "s/-eve//1" | sed -e "s#https://#https://${GIT_USER}:${GIT_PASSWORD}@#1" >> ~/.git-credentials
      - git config --global credential.helper store
      - cd maestro-spectrum
      - git add Dockerfile
      - git commit -m "Auto update"
      - git push origin master
