pipeline:

  eve-clone:
    image: no-cloud.fr/eve
    action: clone
    git_branch: ${BRANCH}

  update-base-image:
    image: no-cloud.fr/eve/docker
    base_image: ${IMAGE}
    tag: ${TAG}
    variable: FROM_DIGEST

  update-spectrum:
    image: no-cloud.fr/eve/git
    repository: ${SPECTRUM}
    branch: master
    variable: SPECTRUM_VERSION

  update-telegram:
    image: no-cloud.fr/eve/git
    repository: https://github.com/majn/telegram-purple
    branch: master
    variable: TELEGRAM_VERSION

  update-hangouts:
    image: no-cloud.fr/eve/bitbucket
    repository: EionRobb/purple-hangouts
    branch: default
    variable: HANGOUTS_VERSION

  eve-push:
    image: no-cloud.fr/eve
    secrets: [ git_user, git_password ]

matrix:
  include:
    - BRANCH: maestro
      IMAGE: library/fedora
      TAG: 27
      SPECTRUM: git://github.com/ArnoBouts/spectrum2.git
    - BRANCH: master
      IMAGE: library/fedora
      TAG: 23
      SPECTRUM: git://github.com/hanzz/spectrum2.git
    - BRANCH: debian
      IMAGE: library/debian
      TAG: jessie
      SPECTRUM: git://github.com/hanzz/spectrum2.git
