pipeline:

  clone:
    image: no-cloud.fr/eve/git
    commands:
      - git clone $(echo ${DRONE_REPO_LINK} | sed -e 's/-eve//1') | sed -e "s#https://#https://${GIT_USER}:${GIT_PASSWORD}@#1"

  update-spectrum:
    image: no-cloud.fr/eve/git
    repository: git://github.com/hanzz/spectrum2.git
    branch: master
    variable: SPECTRUM_VERSION
    file: maestro-spectrum/Dockerfile

  update-telegram:
    image: no-cloud.fr/eve/git
    repository: https://github.com/majn/telegram-purple
    branch: master
    variable: TELEGRAM_VERSION
    file: maestro-spectrum/Dockerfile

  update-hangouts:
    image: no-cloud.fr/eve/bitbucket
    commands:
      - /eve.sh St0ub/purple-hangouts default HANGOUTS_VERSION maestro-spectrum/Dockerfile

  deploy:
    image: no-cloud.fr/eve/git
    commands:
      - cd maestro-spectrum
      - git config --global user.name "Eve"
      - git config --global user.email "eve@no-cloud.fr"
      - git config --global push.default simple
      - git remote get-url origin | sed -e "s#https://#https://${GIT_USER}:${GIT_PASSWORD}@#1" >> ~/.git-credentials
      - git config --global credential.helper store
      - git add Dockerfile
      - git commit -m "Auto update"
      - git remote get-url origin
      - git push
