pipeline:

  clone:
    image: no-cloud.fr/eve/git
    commands:
      - git clone $(echo ${DRONE_REPO_LINK} | sed -e 's/-eve//1') | sed -e "s#https://#https://${GIT_USER}:${GIT_PASSWORD}@#1"

  update-spectrum:
    image: no-cloud.fr/eve/git
    commands:
      - /eve.sh git://github.com/hanzz/spectrum2.git master SPECTRUM_VERSION maestro-spectrum/Dockerfile

  update-telegram:
    image: no-cloud.fr/eve/git
    commands:
      - /eve.sh https://github.com/majn/telegram-purple master TELEGRAM_VERSION maestro-spectrum/Dockerfile

  deploy:
    image: no-cloud.fr/eve/git
    commands:
      - cd maestro-spectrum
      - git config --global user.name "Eve"
      - git config --global user.email "eve@no-cloud.fr"
      - git config --global push.default simple
      - git remote get-url origin | sed -e "s#https://#https://${GIT_USER}:${GIT_PASSWORD}@#1" >> ~/.git-credentials
      - git config --global credential.helper store
      - git add Dockerfile
      - git commit -m "Auto update"
      - git push origin master
